name: Deploy to Subdomain

on:
  push:
    branches:
      - main  # Adjust to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: 65.2.171.237  # Replace with your server's hostname or IP address
      - name: Build JAR
        run: ./gradlew build

      - name: Transfer JAR file to Server
        run: |
          scp -i ${{ secrets.office }} build/libs/your-spring-app.jar ubuntu@ip-172-26-1-31:/www/wwwroot/api.geeknuts.in
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY}}
          SSH_USERNAME: ubuntu@ip-172-26-1-31
      - name: SSH into Remote Server and Run JAR
        run: |
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ${{ secrets.SSH_USERNAME}}@api.geeknuts.in 'cd /www/wwwroot/api.geeknuts.in && java -jar your-spring-app.jar'
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_USERNAME: ubuntu@ip-172-26-1-31
