name: Deploy to Subdomain

on:
  push:
    branches:
      - main  # Adjust to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 65.2.171.237  # Replace with your server's hostname or IP address
          username: ubuntu  # Replace with your SSH username
          key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Build JAR
        run: ./gradlew build

      - name: Transfer JAR file to Server
        run: |
          scp -i ${{ secrets.SSH_PRIVATE_KEY }} build/libs/your-spring-app.jar ubuntu@65.2.171.237:/www/wwwroot/api.geeknuts.in
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    
      - name: SSH into Remote Server and Run JAR
        run: |
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ubuntu@65.2.171.237 'cd /www/wwwroot/api.geeknuts.in && java -jar your-spring-app.jar'
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
