name: Deploy to Subdomain

on:
  push:
    branches:
      - main  # Adjust to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Build JAR
        run: ./gradlew build

      - name: Transfer JAR file to Server
        run: |
          scp -i ${{ secrets.SSH_PRIVATE_KEY }} build/libs/your-spring-app.jar ssh-username@api.geeknuts.in:/path/on/remote/server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_USERNAME: ssh-username

      - name: SSH into Remote Server and Run JAR
        run: |
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ${{ secrets.SSH_USERNAME}}@api.geeknuts.in 'cd /path/on/remote/server && java -jar your-spring-app.jar'
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_USERNAME: ssh-username
