name: Deploy to Subdomain

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      - name: Build & Deploy
        env:
            PRIVATE_KEY: ${{ secrets.LIGHTSAIL_PRIVATE_KEY }}
            HOSTNAME: ${{secrets.LIGHTSAIL_HOST}}
            USER_NAME: ${{secrets.LIGHTSAIL_USERNAME}}
      
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME}
 


      #- name: Check SSH connection
        #run: ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ubuntu@65.2.171.237 "echo 'SSH connection successful ff'"


      - name: Build JAR
        run: ./gradlew build

      - name: List Local Directories
        run: |
          ls build/libs
          ls src

      - name: Transfer JAR file to Server
        run: scp -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} build/libs/api-0.0.1.jar ubuntu@65.2.171.237:/www/wwwroot/api.geeknuts.in

     # - name: SSH into Remote Server and Run JAR
       # run: ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} ubuntu@65.2.171.237 'cd /www/wwwroot/api.geeknuts.in && java -jar api-0.0.1.jar'
